[ pid=19651 thr=70914400 file=utils.rb:176 time=2011-05-06 22:40:26.608 ]: *** Exception PhusionPassenger::UnknownError in PhusionPassenger::Rack::ApplicationSpawner (Bundler could not find compatible versions for gem "activesupport":
  In snapshot (Gemfile.lock):
    activesupport (3.0.3)

  In Gemfile:
    rails (>= 3.0.7) depends on
      activesupport (= 3.0.7)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
 (Bundler::VersionConflict)) (process 19651, thread #<Thread:0x87422c0>):
	from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.13/lib/bundler/resolver.rb:129:in `block in resolve'
	from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.13/lib/bundler/resolver.rb:127:in `catch'
	from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.13/lib/bundler/resolver.rb:127:in `resolve'
	from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.13/lib/bundler/definition.rb:151:in `resolve'
	from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.13/lib/bundler/definition.rb:90:in `specs'
	from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.13/lib/bundler/definition.rb:135:in `specs_for'
	from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.13/lib/bundler/definition.rb:124:in `requested_specs'
	from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.13/lib/bundler/environment.rb:23:in `requested_specs'
	from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.13/lib/bundler/runtime.rb:11:in `setup'
	from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.13/lib/bundler.rb:107:in `setup'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/lib/phusion_passenger/utils.rb:326:in `prepare_app_process'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/lib/phusion_passenger/rack/application_spawner.rb:155:in `block in initialize_server'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/lib/phusion_passenger/utils.rb:572:in `report_app_init_status'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/lib/phusion_passenger/rack/application_spawner.rb:153:in `initialize_server'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/lib/phusion_passenger/abstract_server.rb:204:in `start_synchronously'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/lib/phusion_passenger/abstract_server.rb:180:in `start'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/lib/phusion_passenger/rack/application_spawner.rb:128:in `start'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/lib/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/lib/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
	from <internal:prelude>:10:in `synchronize'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
	from /var/lib/passenger-standalone/3.0.7-x86-ruby1.9.2-linux-gcc4.1.2-1002/support/helper-scripts/passenger-spawn-server:99:in `<main>'
[ pid=19649 thr=3072752528 file=ext/nginx/HelperAgent.cpp:584 time=2011-05-06 22:40:26.717 ]: Uncaught exception in PassengerServer client thread:
   exception: write() failed: Broken pipe (32)
   backtrace:
     in 'void Client::handleRequest(Passenger::FileDescriptor&)' (HelperAgent.cpp:479)
     in 'void Client::threadMain()' (HelperAgent.cpp:603)

Rails Error: Unable to access log file. Please ensure that /railsapp/12doo/log/production.log exists and is chmod 0666. The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
[ pid=19753 thr=3072920464 file=ext/nginx/HelperAgent.cpp:574 time=2011-05-06 22:41:58.499 ]: Couldn't forward the HTTP response back to the HTTP client: It seems the user clicked on the 'Stop' button in his browser.

ActionController::RoutingError (No route matches "/images/TITLE01.gif"):
  


ActionController::RoutingError (No route matches "/images/TITLE02.gif"):
  


ActionController::RoutingError (No route matches "/images/TITLE03.gif"):
  


ActionController::RoutingError (No route matches "/images/TITLE04.gif"):
  


ActionController::RoutingError (No route matches "/images/TITLE05.gif"):
  

Rails Error: Unable to access log file. Please ensure that /railsapp/12doo/log/production.log exists and is chmod 0666. The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
[ pid=19917 thr=3072736144 file=ext/nginx/HelperAgent.cpp:574 time=2011-05-06 22:44:11.31 ]: Couldn't forward the HTTP response back to the HTTP client: It seems the user clicked on the 'Stop' button in his browser.
Rails Error: Unable to access log file. Please ensure that /railsapp/12doo/log/development.log exists and is chmod 0666. The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.

Mysql2::Error (Unknown database '12doo-dev'):
  

[ pid=28292 thr=3073346448 file=ext/nginx/HelperAgent.cpp:574 time=2011-05-07 19:43:38.335 ]: Couldn't forward the HTTP response back to the HTTP client: It seems the user clicked on the 'Stop' button in his browser.
Rails Error: Unable to access log file. Please ensure that /railsapp/12doo/log/production.log exists and is chmod 0666. The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
[ pid=28381 thr=3072932752 file=ext/nginx/HelperAgent.cpp:574 time=2011-05-07 19:44:03.325 ]: Couldn't forward the HTTP response back to the HTTP client: It seems the user clicked on the 'Stop' button in his browser.

ActionController::RoutingError (No route matches "/item/100326.html"):
  

2011/05/17 21:19:55 [error] 5739#0: *4 "/railsapp/12doo/public/index.html" is forbidden (13: Permission denied), client: 127.0.0.1, server: _, request: "HEAD / HTTP/1.1", host: "0.0.0.0"
